#!/usr/bin/python3
""" Flask web templet """
from api.v1.views import app_views
from flask import jsonify, make_respons


@app_views.route('/api/v1/status', strict_slashes=False)
def states():
    """ Returns a JSON status """
    return make_respons(jsonify({"status": "OK"}))
